### ISSUE TITLE
Config-Problem / Generally no output

### ISSUE THREAD

**Issue by AMC2000** [tsuriga/csgo-gsi-qsguide#2]
Hey, so im totally new to node.js and csgo gsi, but i have some problems getting into it...
When im executing the config for csgo (gamestate_integration_...) a map called 'am_Water2014' is loading and im alone on the map, no bots, nothing.

I guess thats also the issue why im getting no output in the cmd as well...
any idea how to fix this weird behaivor after running the config?

Same with the 'official' config from https://developer.valvesoftware.com/wiki/Counter-Strike:_Global_Offensive_Game_State_Integration

Hope to get Some Help... even tho this might not be the thing, issues on github are for, but sadly im not able to get any information from google...

**Comment by tsuriga** [comment]
The quickstartguide.js picks up only on round and map ends by default, which may not be the best approach now that you mention it since it requires very specific things to happen for you to see any output. I'll remedy that. In the meanwhile you should be seeing something if you load up a map with bots and play some rounds, or have the program running in the background while you play some actual matches. Or, you can run `node outputpayloads.js` which will output all the payloads that CS:GO GSI sends out.

Also note that if you're using another config you'll need to change the token, otherwise you won't be seeing any output either as any payloads will be considered unauthorized and skipped if the tokens don't match. Search the code and config file for "token" and you'll see how it's verified.

**Comment by FlowingSPDG** [comment]
You don't need to execute gamestate_integration...cfg file.
CS:GO will load those configs automaticly when launches game.

**Comment by tsuriga** [comment]
Updated README
